name: Publish package on pypi

on:
  push:
    branches: [master]

jobs:
  publish-flow:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    steps:
      - name: Check out repository
        uses: actions/checkout@v6

      - name: Install uv
        uses: astral-sh/setup-uv@v7

      - name: Set up Python
        run: uv python install
    

      - name: Install the project
        run: uv sync --locked --all-extras --dev

      - name: Run tests
        run: uv run pytest

        # publish version only when pyproject.toml is changed in master
      - name: Filter changes in pyproject
        uses: dorny/paths-filter@v2
        id: changes
        with:
          filters: |
            root:
              - 'pyproject.toml'

      - if: ${{ (github.ref == 'refs/heads/master') && (steps.changes.outputs.root == 'true')}}
        name: Build
        run: uv build

      - if: ${{ (github.ref == 'refs/heads/master') && (steps.changes.outputs.root == 'true')}}
        name: Publish release distributions to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
